---
docker_kernel_min_version: '3.10'

# https://download.docker.com/linux/ubuntu/
docker_versioned_pkg:
  'latest': docker.io
  '19.03': docker.io=19.03.8-0ubuntu1
  'stable': docker.io=19.03.8-0ubuntu1

docker_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      force: yes

docker_repo_key_info:
  pkg_key: apt_key
  url: '{{ docker_ubuntu_repo_gpgkey }}'
  repo_keys:
    - 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

docker_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
       deb {{ docker_ubuntu_repo_base_url }}
       bionic
       stable

dockerproject_repo_key_info:
  pkg_key: apt_key
  url: '{{ docker_ubuntu_repo_gpgkey }}'
  repo_keys:
    - 58118E89F3A912897C070ADBF76221572C52609D

dockerproject_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
       deb {{ docker_ubuntu_repo_base_url }}
       {{ ansible_distribution|lower }}-bionic
       main
